# Floortile problem
# 1 robot, 2D

reset;
model floortile2D.mod;
data  floortile2D.dat;

option solver ilogcp;
printf "\n** Before solve **\n\n";
solve;

printf "\n** Results**\n\n", n;
display x;
display y;
display stock0;
display stock1;
display color;
display move;
display paint;
display switch;
display cell;
display _ampl_elapsed_time;
printf "\n ** For 2D floortile, with %g x %g cells and 1 robot : **\n", n, m;
printf "==> Board complete after %g time steps\n\n", tstar;
   
